version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: mindflora_ollama
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mindflora_backend
    volumes:
      - .:/app
      - /app/mindflora
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - PYTHONPATH=/app
      - ENVIRONMENT=development
    ports:
      - "8000:8000"
    depends_on:
      ollama:
        condition: service_healthy
    command: uvicorn api_gateway.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    image: nginx:alpine
    container_name: mindflora_frontend
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  ollama_data:
    name: mindflora_ollama_data 